try
    {
    throw new T('exception');
    }
catch(E exc)
    {
        print('hello world');
    }